name: flutter_login
description: A new Flutter application to demonstrate an auth flow.
version: 1.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.0
  get_version: ^0.0.8+5
  flutter_whatsnew: ^0.2.0+3
  native_widgets: ^1.0.1
  shared_preferences: ^0.5.1+1
  local_auth: ^0.4.0+1
  cupertino_icons: ^0.1.2
  persist_theme: ^0.0.3+6
  scoped_model: ^1.0.1
  http: ^0.12.0+1
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/login_contact.png
   - CHANGELOG.md
